# GitHub Pages configuration
# This file configures how GitHub Pages serves the site

# Site settings
title: "PLP - Passion Lab Polimi"
description: "PLP - Professional Learning Platform"
url: "https://passionlabpolimi.it"
baseurl: ""

# Build settings
source: .
destination: out
plugins:
  - jekyll-sitemap
  - jekyll-feed

# Exclude files from processing
exclude:
  - node_modules
  - .git
  - .github
  - package.json
  - package-lock.json
  - next.config.ts
  - tsconfig.json
  - README.md

# Include files
include:
  - _redirects
  - .nojekyll

# Collections
collections:
  pages:
    output: true
    permalink: /:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Markdown settings
markdown: kramdown
highlighter: rouge

# Sass settings
sass:
  sass_dir: _sass
  style: compressed

# Pagination
paginate: 5
paginate_path: "/page:num/"

# Timezone
timezone: Europe/Rome

# Encoding
encoding: utf-8
